# -*- coding: utf-8 -*-
"""day2(03/03/2020)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q9NXYeiLBxFkph1bUmfBYjy7sX95L_3Q

accept a string as input and convert lower case into uppercase and vice versa
"""

n = input()
for i in range n:
  ord(n[i])

"""find(),c#t"""

s1 = "abc xyz"
s2 = "xyz"
print(s1.find(s2))
print(s1.find("uvw"))
print(s1.isalpha())# returns false
print(s2.isalpha())# returns true
print(s1.isalnum())# returns false
print(s2.isalnum())# retruns ture
print(s1.swapcase())#ABC XYZ
print(s1.split())#takes space as default value and splits the string

"""## **Operators**: They perform operations on operands
1. Arithmatic operators:  +, -, * , /, %, //, **
2. Logical operators: and, or, not
3. Assignment operators: =, +=, -=, *=, /=, %=, //=, **=
4. Relational operators: <, >, <=,>=, =, ==, !=
5. Bitwise operators: &,|, ^, ~, <<,>>
6. Membership operators: in,not in
7. Identity operators: is, is not
8. Ternary operators:
"""

#bitwise operators
x=10 #0000 1010
y=20 #0001 0100
print(x & y)
print(x | y)#0001 1110
print(x^ y)#0001 1110
print(x << y)
print(x >> y)
print(~x)

bin(x)

bin(y)

#Identity operators
x=10
y=20
z=10
print(x is z)
print(x is not z)

#Teraditional if-else
x = 10
y = 20
if(x>y):
  print(x)
else:
  print(y)
#Ternary operators
print(x) if (x>y) else print(y)

"""#Conditional control statements
1. if
2. else
3. elif
"""

#Accept marks of 3 subjects, check whether student got minimum 30 in all subjects. 
#If he gets minimum 30 in all subjects, then file avg marks of the student. else print fail.
#If avg >=75, print A. avg >=60 and avg <75, print B
#avg <60 and avg >=45, print C
#avg <45 and avg >= 30, print D


a = int(input("1st subject marks: "))
b = int(input("2nd subject marks: "))
c = int(input("3rd subject marks: "))
if (a<30 or b<30 or c<30):
  print("fail")
else:
  D=(a+b+c)/3
  if(D>=74):
    print("Grade is A", "average is ",D)
  elif(D<75 and D>=60):
    print("Grade is B", "average is ",D)
  elif(D<60 and D>=45):
    print("Grade is C", "average is ",D)
  elif(D<45 and D>=30):
    print("Grade is D", "average is ",D)
  else:
    print("fail")

#Loops: while, for
#to perform repeative functions

i = 1
n = int(input("Enter any value: "))
while i <= n:
  print(i, end='')
  i+=1
print()
for i in range(1, n+1):
  print(i, end='')

#Accept a string as an input and print all characters without using len()
#use while

s1 = input()
count = 0
j = 0
for i in s1:#counting no.of characters
  count+=1
print(count)
while j<count:#print the characters
  print(s1[j])
  j+=1

#Accept a string as an input
#check whether the string is palindrome or not

a = input()
if a == a[::-1]:
  print("palindrome")
else:
  print("not a palindrome")

#ternary operators
print("palindrome") if a == a[::-1] else print("not a palindrome")

#check palindrome for numbers

n = int(input())
s = 
print (s, m)